apiVersion: v1
kind: Service
metadata:
  name: testground-sync-service-headless
  labels:
    app: testground-sync-service-headless
spec:
  clusterIP: None
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 5050
  selector:
    app: testground-sync-service
